//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLPK
{
    using System;
    using System.Collections.Generic;
    
    public partial class BacSi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BacSi()
        {
            this.BenhNhans = new HashSet<BenhNhan>();
        }
    
        public string MaBS { get; set; }
        public string HoBS { get; set; }
        public string TenBS { get; set; }
        public string DiaChi { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public Nullable<bool> GioiTinh { get; set; }
        public string SDT { get; set; }
        public string Nhom { get; set; }
        public Nullable<decimal> Luong { get; set; }
        public string Khoa { get; set; }
        public Nullable<bool> Deleted { get; set; }
    
        public virtual Khoa Khoa1 { get; set; }
        public virtual NhomDoiTuong NhomDoiTuong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BenhNhan> BenhNhans { get; set; }
    }
}
