//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLPK
{
    using System;
    using System.Collections.Generic;
    
    public partial class BenhNhan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BenhNhan()
        {
            this.BenhAns = new HashSet<BenhAn>();
            this.BenhAns1 = new HashSet<BenhAn>();
            this.HoaDons = new HashSet<HoaDon>();
            this.PhieuNhapViens = new HashSet<PhieuNhapVien>();
            this.PhieuXetNghiems = new HashSet<PhieuXetNghiem>();
            this.PhieuXuatViens = new HashSet<PhieuXuatVien>();
            this.PhieuDieuTris = new HashSet<PhieuDieuTri>();
        }
    
        public string MaBenhNhan { get; set; }
        public string HoBN { get; set; }
        public string TenBN { get; set; }
        public string DiaChi { get; set; }
        public Nullable<bool> GioiTinh { get; set; }
        public string Khoa { get; set; }
        public string Nhom { get; set; }
        public string BacSi { get; set; }
        public int SDT { get; set; }
        public System.DateTime NgaySinh { get; set; }
        public Nullable<bool> Deleted { get; set; }
    
        public virtual BacSi BacSi1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BenhAn> BenhAns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BenhAn> BenhAns1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDon> HoaDons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuNhapVien> PhieuNhapViens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuXetNghiem> PhieuXetNghiems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuXuatVien> PhieuXuatViens { get; set; }
        public virtual Khoa Khoa1 { get; set; }
        public virtual NhomDoiTuong NhomDoiTuong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuDieuTri> PhieuDieuTris { get; set; }
    }
}
