//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLPK
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonThuoc
    {
        public string MaDT { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public string HuongDan { get; set; }
        public string MaThuoc { get; set; }
        public string BenhNhan { get; set; }
    
        public virtual Thuoc Thuoc { get; set; }
    }
}
