//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLPK
{
    using System;
    using System.Collections.Generic;
    
    public partial class Giuong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Giuong()
        {
            this.PhieuNhapViens = new HashSet<PhieuNhapVien>();
        }
    
        public string MaGiuong { get; set; }
        public string Phong { get; set; }
        public Nullable<bool> Book { get; set; }
    
        public virtual Phong Phong1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuNhapVien> PhieuNhapViens { get; set; }
    }
}
