//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLPK
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public string MaHD { get; set; }
        public string DichVu { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public string NguoiLap { get; set; }
        public string BenhNhan { get; set; }
        public Nullable<System.DateTime> NgayKham { get; set; }
    
        public virtual BenhNhan BenhNhan1 { get; set; }
        public virtual DichVu DichVu1 { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
