//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLPK
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class qlpk1Entities2 : DbContext
    {
        public qlpk1Entities2()
            : base("name=qlpk1Entities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BacSi> BacSis { get; set; }
        public virtual DbSet<BenhAn> BenhAns { get; set; }
        public virtual DbSet<BenhNhan> BenhNhans { get; set; }
        public virtual DbSet<DichVu> DichVus { get; set; }
        public virtual DbSet<DonThuoc> DonThuocs { get; set; }
        public virtual DbSet<Giuong> Giuongs { get; set; }
        public virtual DbSet<HoaDon> HoaDons { get; set; }
        public virtual DbSet<Khoa> Khoas { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<NhomDoiTuong> NhomDoiTuongs { get; set; }
        public virtual DbSet<PhieuDieuTri> PhieuDieuTris { get; set; }
        public virtual DbSet<PhieuNhapVien> PhieuNhapViens { get; set; }
        public virtual DbSet<PhieuXetNghiem> PhieuXetNghiems { get; set; }
        public virtual DbSet<PhieuXuatVien> PhieuXuatViens { get; set; }
        public virtual DbSet<Phong> Phongs { get; set; }
        public virtual DbSet<Thuoc> Thuocs { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<v_Current_BenhNhan> v_Current_BenhNhan { get; set; }
        public virtual DbSet<v_Deleted_BenhNhan> v_Deleted_BenhNhan { get; set; }
        public virtual DbSet<v_LoadBNNT> v_LoadBNNT { get; set; }
        public virtual DbSet<v_NoiTru> v_NoiTru { get; set; }
        public virtual DbSet<v_ShowPhong> v_ShowPhong { get; set; }
        public virtual DbSet<v_Select_BenhAnNotNull> v_Select_BenhAnNotNull { get; set; }
        public virtual DbSet<v_Select_BenhAnNull> v_Select_BenhAnNull { get; set; }
    
        public virtual int usp__Delete__BenhAn(string maBA)
        {
            var maBAParameter = maBA != null ?
                new ObjectParameter("maBA", maBA) :
                new ObjectParameter("maBA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp__Delete__BenhAn", maBAParameter);
        }
    
        public virtual int usp__Delete__DT(string madt)
        {
            var madtParameter = madt != null ?
                new ObjectParameter("madt", madt) :
                new ObjectParameter("madt", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp__Delete__DT", madtParameter);
        }
    
        public virtual int usp__Delete__DV(string madv)
        {
            var madvParameter = madv != null ?
                new ObjectParameter("madv", madv) :
                new ObjectParameter("madv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp__Delete__DV", madvParameter);
        }
    
        public virtual int usp__Delete__Phong(string map)
        {
            var mapParameter = map != null ?
                new ObjectParameter("map", map) :
                new ObjectParameter("map", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp__Delete__Phong", mapParameter);
        }
    
        public virtual int usp__Delete__PNV(string mapnv)
        {
            var mapnvParameter = mapnv != null ?
                new ObjectParameter("mapnv", mapnv) :
                new ObjectParameter("mapnv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp__Delete__PNV", mapnvParameter);
        }
    
        public virtual int usp__Delete__PXN(string mapxn)
        {
            var mapxnParameter = mapxn != null ?
                new ObjectParameter("mapxn", mapxn) :
                new ObjectParameter("mapxn", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp__Delete__PXN", mapxnParameter);
        }
    
        public virtual int usp__Delete__PXV(string mapxv)
        {
            var mapxvParameter = mapxv != null ?
                new ObjectParameter("mapxv", mapxv) :
                new ObjectParameter("mapxv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp__Delete__PXV", mapxvParameter);
        }
    
        public virtual int usp__Delete__Thuoc(string mat)
        {
            var matParameter = mat != null ?
                new ObjectParameter("mat", mat) :
                new ObjectParameter("mat", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp__Delete__Thuoc", matParameter);
        }
    
        public virtual int usp__Insert__BenhAn(string maBA)
        {
            var maBAParameter = maBA != null ?
                new ObjectParameter("maBA", maBA) :
                new ObjectParameter("maBA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp__Insert__BenhAn", maBAParameter);
        }
    
        public virtual int usp__Insert__DT(string madt, Nullable<int> sl, string hd, string mt, string bn)
        {
            var madtParameter = madt != null ?
                new ObjectParameter("madt", madt) :
                new ObjectParameter("madt", typeof(string));
    
            var slParameter = sl.HasValue ?
                new ObjectParameter("sl", sl) :
                new ObjectParameter("sl", typeof(int));
    
            var hdParameter = hd != null ?
                new ObjectParameter("hd", hd) :
                new ObjectParameter("hd", typeof(string));
    
            var mtParameter = mt != null ?
                new ObjectParameter("mt", mt) :
                new ObjectParameter("mt", typeof(string));
    
            var bnParameter = bn != null ?
                new ObjectParameter("bn", bn) :
                new ObjectParameter("bn", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp__Insert__DT", madtParameter, slParameter, hdParameter, mtParameter, bnParameter);
        }
    
        public virtual int usp__Insert__DV(string madv, string tdv, string dvt, Nullable<decimal> dg)
        {
            var madvParameter = madv != null ?
                new ObjectParameter("madv", madv) :
                new ObjectParameter("madv", typeof(string));
    
            var tdvParameter = tdv != null ?
                new ObjectParameter("tdv", tdv) :
                new ObjectParameter("tdv", typeof(string));
    
            var dvtParameter = dvt != null ?
                new ObjectParameter("dvt", dvt) :
                new ObjectParameter("dvt", typeof(string));
    
            var dgParameter = dg.HasValue ?
                new ObjectParameter("dg", dg) :
                new ObjectParameter("dg", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp__Insert__DV", madvParameter, tdvParameter, dvtParameter, dgParameter);
        }
    
        public virtual int usp__Insert__Phong(string map, string tp, string k)
        {
            var mapParameter = map != null ?
                new ObjectParameter("map", map) :
                new ObjectParameter("map", typeof(string));
    
            var tpParameter = tp != null ?
                new ObjectParameter("tp", tp) :
                new ObjectParameter("tp", typeof(string));
    
            var kParameter = k != null ?
                new ObjectParameter("k", k) :
                new ObjectParameter("k", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp__Insert__Phong", mapParameter, tpParameter, kParameter);
        }
    
        public virtual int usp__Insert__PNV(string mapnv, Nullable<System.DateTime> tgnv, Nullable<System.DateTime> nl, string khoa, string bn, string ngl, string gig)
        {
            var mapnvParameter = mapnv != null ?
                new ObjectParameter("mapnv", mapnv) :
                new ObjectParameter("mapnv", typeof(string));
    
            var tgnvParameter = tgnv.HasValue ?
                new ObjectParameter("tgnv", tgnv) :
                new ObjectParameter("tgnv", typeof(System.DateTime));
    
            var nlParameter = nl.HasValue ?
                new ObjectParameter("nl", nl) :
                new ObjectParameter("nl", typeof(System.DateTime));
    
            var khoaParameter = khoa != null ?
                new ObjectParameter("khoa", khoa) :
                new ObjectParameter("khoa", typeof(string));
    
            var bnParameter = bn != null ?
                new ObjectParameter("bn", bn) :
                new ObjectParameter("bn", typeof(string));
    
            var nglParameter = ngl != null ?
                new ObjectParameter("ngl", ngl) :
                new ObjectParameter("ngl", typeof(string));
    
            var gigParameter = gig != null ?
                new ObjectParameter("gig", gig) :
                new ObjectParameter("gig", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp__Insert__PNV", mapnvParameter, tgnvParameter, nlParameter, khoaParameter, bnParameter, nglParameter, gigParameter);
        }
    
        public virtual int usp__Insert__PXN(string mapxn, string tlxn, Nullable<System.DateTime> nxn, string kq, string gc, string bn)
        {
            var mapxnParameter = mapxn != null ?
                new ObjectParameter("mapxn", mapxn) :
                new ObjectParameter("mapxn", typeof(string));
    
            var tlxnParameter = tlxn != null ?
                new ObjectParameter("tlxn", tlxn) :
                new ObjectParameter("tlxn", typeof(string));
    
            var nxnParameter = nxn.HasValue ?
                new ObjectParameter("nxn", nxn) :
                new ObjectParameter("nxn", typeof(System.DateTime));
    
            var kqParameter = kq != null ?
                new ObjectParameter("kq", kq) :
                new ObjectParameter("kq", typeof(string));
    
            var gcParameter = gc != null ?
                new ObjectParameter("gc", gc) :
                new ObjectParameter("gc", typeof(string));
    
            var bnParameter = bn != null ?
                new ObjectParameter("bn", bn) :
                new ObjectParameter("bn", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp__Insert__PXN", mapxnParameter, tlxnParameter, nxnParameter, kqParameter, gcParameter, bnParameter);
        }
    
        public virtual int usp__Insert__PXV(string mapxv, Nullable<System.DateTime> tgdt, Nullable<System.DateTime> nl, string khoa, string bn)
        {
            var mapxvParameter = mapxv != null ?
                new ObjectParameter("mapxv", mapxv) :
                new ObjectParameter("mapxv", typeof(string));
    
            var tgdtParameter = tgdt.HasValue ?
                new ObjectParameter("tgdt", tgdt) :
                new ObjectParameter("tgdt", typeof(System.DateTime));
    
            var nlParameter = nl.HasValue ?
                new ObjectParameter("nl", nl) :
                new ObjectParameter("nl", typeof(System.DateTime));
    
            var khoaParameter = khoa != null ?
                new ObjectParameter("khoa", khoa) :
                new ObjectParameter("khoa", typeof(string));
    
            var bnParameter = bn != null ?
                new ObjectParameter("bn", bn) :
                new ObjectParameter("bn", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp__Insert__PXV", mapxvParameter, tgdtParameter, nlParameter, khoaParameter, bnParameter);
        }
    
        public virtual int usp__Insert__Thuoc(string mat, string tenth, string td, Nullable<decimal> gia, Nullable<int> sl)
        {
            var matParameter = mat != null ?
                new ObjectParameter("mat", mat) :
                new ObjectParameter("mat", typeof(string));
    
            var tenthParameter = tenth != null ?
                new ObjectParameter("tenth", tenth) :
                new ObjectParameter("tenth", typeof(string));
    
            var tdParameter = td != null ?
                new ObjectParameter("td", td) :
                new ObjectParameter("td", typeof(string));
    
            var giaParameter = gia.HasValue ?
                new ObjectParameter("gia", gia) :
                new ObjectParameter("gia", typeof(decimal));
    
            var slParameter = sl.HasValue ?
                new ObjectParameter("sl", sl) :
                new ObjectParameter("sl", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp__Insert__Thuoc", matParameter, tenthParameter, tdParameter, giaParameter, slParameter);
        }
    
        public virtual int usp__Update__DT(string madt, Nullable<int> sl, string hd, string mt)
        {
            var madtParameter = madt != null ?
                new ObjectParameter("madt", madt) :
                new ObjectParameter("madt", typeof(string));
    
            var slParameter = sl.HasValue ?
                new ObjectParameter("sl", sl) :
                new ObjectParameter("sl", typeof(int));
    
            var hdParameter = hd != null ?
                new ObjectParameter("hd", hd) :
                new ObjectParameter("hd", typeof(string));
    
            var mtParameter = mt != null ?
                new ObjectParameter("mt", mt) :
                new ObjectParameter("mt", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp__Update__DT", madtParameter, slParameter, hdParameter, mtParameter);
        }
    
        public virtual int usp__Update__DV(string madv, string tdv, string dvt, Nullable<decimal> dg)
        {
            var madvParameter = madv != null ?
                new ObjectParameter("madv", madv) :
                new ObjectParameter("madv", typeof(string));
    
            var tdvParameter = tdv != null ?
                new ObjectParameter("tdv", tdv) :
                new ObjectParameter("tdv", typeof(string));
    
            var dvtParameter = dvt != null ?
                new ObjectParameter("dvt", dvt) :
                new ObjectParameter("dvt", typeof(string));
    
            var dgParameter = dg.HasValue ?
                new ObjectParameter("dg", dg) :
                new ObjectParameter("dg", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp__Update__DV", madvParameter, tdvParameter, dvtParameter, dgParameter);
        }
    
        public virtual int usp__Update__Phong(string map, string tp, string k)
        {
            var mapParameter = map != null ?
                new ObjectParameter("map", map) :
                new ObjectParameter("map", typeof(string));
    
            var tpParameter = tp != null ?
                new ObjectParameter("tp", tp) :
                new ObjectParameter("tp", typeof(string));
    
            var kParameter = k != null ?
                new ObjectParameter("k", k) :
                new ObjectParameter("k", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp__Update__Phong", mapParameter, tpParameter, kParameter);
        }
    
        public virtual int usp__Update__PNV(string mapnv, Nullable<System.DateTime> tgnv, Nullable<System.DateTime> nl, string khoa, string bn, string ngl)
        {
            var mapnvParameter = mapnv != null ?
                new ObjectParameter("mapnv", mapnv) :
                new ObjectParameter("mapnv", typeof(string));
    
            var tgnvParameter = tgnv.HasValue ?
                new ObjectParameter("tgnv", tgnv) :
                new ObjectParameter("tgnv", typeof(System.DateTime));
    
            var nlParameter = nl.HasValue ?
                new ObjectParameter("nl", nl) :
                new ObjectParameter("nl", typeof(System.DateTime));
    
            var khoaParameter = khoa != null ?
                new ObjectParameter("khoa", khoa) :
                new ObjectParameter("khoa", typeof(string));
    
            var bnParameter = bn != null ?
                new ObjectParameter("bn", bn) :
                new ObjectParameter("bn", typeof(string));
    
            var nglParameter = ngl != null ?
                new ObjectParameter("ngl", ngl) :
                new ObjectParameter("ngl", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp__Update__PNV", mapnvParameter, tgnvParameter, nlParameter, khoaParameter, bnParameter, nglParameter);
        }
    
        public virtual int usp__Update__PXN(string mapxn, string tlxn, Nullable<System.DateTime> nxn, string kq, string gc, string bn)
        {
            var mapxnParameter = mapxn != null ?
                new ObjectParameter("mapxn", mapxn) :
                new ObjectParameter("mapxn", typeof(string));
    
            var tlxnParameter = tlxn != null ?
                new ObjectParameter("tlxn", tlxn) :
                new ObjectParameter("tlxn", typeof(string));
    
            var nxnParameter = nxn.HasValue ?
                new ObjectParameter("nxn", nxn) :
                new ObjectParameter("nxn", typeof(System.DateTime));
    
            var kqParameter = kq != null ?
                new ObjectParameter("kq", kq) :
                new ObjectParameter("kq", typeof(string));
    
            var gcParameter = gc != null ?
                new ObjectParameter("gc", gc) :
                new ObjectParameter("gc", typeof(string));
    
            var bnParameter = bn != null ?
                new ObjectParameter("bn", bn) :
                new ObjectParameter("bn", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp__Update__PXN", mapxnParameter, tlxnParameter, nxnParameter, kqParameter, gcParameter, bnParameter);
        }
    
        public virtual int usp__Update__PXV(string mapxv, Nullable<System.DateTime> tgdt, Nullable<System.DateTime> nl, string khoa, string bn)
        {
            var mapxvParameter = mapxv != null ?
                new ObjectParameter("mapxv", mapxv) :
                new ObjectParameter("mapxv", typeof(string));
    
            var tgdtParameter = tgdt.HasValue ?
                new ObjectParameter("tgdt", tgdt) :
                new ObjectParameter("tgdt", typeof(System.DateTime));
    
            var nlParameter = nl.HasValue ?
                new ObjectParameter("nl", nl) :
                new ObjectParameter("nl", typeof(System.DateTime));
    
            var khoaParameter = khoa != null ?
                new ObjectParameter("khoa", khoa) :
                new ObjectParameter("khoa", typeof(string));
    
            var bnParameter = bn != null ?
                new ObjectParameter("bn", bn) :
                new ObjectParameter("bn", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp__Update__PXV", mapxvParameter, tgdtParameter, nlParameter, khoaParameter, bnParameter);
        }
    
        public virtual int usp__Update__Thuoc(string mat, string tenth, string td, Nullable<decimal> gia, Nullable<int> sl)
        {
            var matParameter = mat != null ?
                new ObjectParameter("mat", mat) :
                new ObjectParameter("mat", typeof(string));
    
            var tenthParameter = tenth != null ?
                new ObjectParameter("tenth", tenth) :
                new ObjectParameter("tenth", typeof(string));
    
            var tdParameter = td != null ?
                new ObjectParameter("td", td) :
                new ObjectParameter("td", typeof(string));
    
            var giaParameter = gia.HasValue ?
                new ObjectParameter("gia", gia) :
                new ObjectParameter("gia", typeof(decimal));
    
            var slParameter = sl.HasValue ?
                new ObjectParameter("sl", sl) :
                new ObjectParameter("sl", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp__Update__Thuoc", matParameter, tenthParameter, tdParameter, giaParameter, slParameter);
        }
    
        public virtual int usp_Delete_BacSi(string mabs)
        {
            var mabsParameter = mabs != null ?
                new ObjectParameter("mabs", mabs) :
                new ObjectParameter("mabs", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_Delete_BacSi", mabsParameter);
        }
    
        public virtual int usp_Delete_BenhNhan(string mabn)
        {
            var mabnParameter = mabn != null ?
                new ObjectParameter("mabn", mabn) :
                new ObjectParameter("mabn", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_Delete_BenhNhan", mabnParameter);
        }
    
        public virtual int usp_delete_DT(string mdt)
        {
            var mdtParameter = mdt != null ?
                new ObjectParameter("mdt", mdt) :
                new ObjectParameter("mdt", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_delete_DT", mdtParameter);
        }
    
        public virtual int usp_Delete_HD(string mhd, string dv)
        {
            var mhdParameter = mhd != null ?
                new ObjectParameter("mhd", mhd) :
                new ObjectParameter("mhd", typeof(string));
    
            var dvParameter = dv != null ?
                new ObjectParameter("dv", dv) :
                new ObjectParameter("dv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_Delete_HD", mhdParameter, dvParameter);
        }
    
        public virtual int usp_Delete_Khoa(string mak)
        {
            var makParameter = mak != null ?
                new ObjectParameter("mak", mak) :
                new ObjectParameter("mak", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_Delete_Khoa", makParameter);
        }
    
        public virtual int usp_Delete_NhanVien(string manv)
        {
            var manvParameter = manv != null ?
                new ObjectParameter("manv", manv) :
                new ObjectParameter("manv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_Delete_NhanVien", manvParameter);
        }
    
        public virtual int usp_Insert_BacSi(string mabs, string hbs, string tbs, string dc, Nullable<System.DateTime> ns, Nullable<bool> gt, string sdt, string nhom, Nullable<decimal> luong, string khoa)
        {
            var mabsParameter = mabs != null ?
                new ObjectParameter("mabs", mabs) :
                new ObjectParameter("mabs", typeof(string));
    
            var hbsParameter = hbs != null ?
                new ObjectParameter("hbs", hbs) :
                new ObjectParameter("hbs", typeof(string));
    
            var tbsParameter = tbs != null ?
                new ObjectParameter("tbs", tbs) :
                new ObjectParameter("tbs", typeof(string));
    
            var dcParameter = dc != null ?
                new ObjectParameter("dc", dc) :
                new ObjectParameter("dc", typeof(string));
    
            var nsParameter = ns.HasValue ?
                new ObjectParameter("ns", ns) :
                new ObjectParameter("ns", typeof(System.DateTime));
    
            var gtParameter = gt.HasValue ?
                new ObjectParameter("gt", gt) :
                new ObjectParameter("gt", typeof(bool));
    
            var sdtParameter = sdt != null ?
                new ObjectParameter("sdt", sdt) :
                new ObjectParameter("sdt", typeof(string));
    
            var nhomParameter = nhom != null ?
                new ObjectParameter("nhom", nhom) :
                new ObjectParameter("nhom", typeof(string));
    
            var luongParameter = luong.HasValue ?
                new ObjectParameter("luong", luong) :
                new ObjectParameter("luong", typeof(decimal));
    
            var khoaParameter = khoa != null ?
                new ObjectParameter("khoa", khoa) :
                new ObjectParameter("khoa", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_Insert_BacSi", mabsParameter, hbsParameter, tbsParameter, dcParameter, nsParameter, gtParameter, sdtParameter, nhomParameter, luongParameter, khoaParameter);
        }
    
        public virtual int usp_Insert_BenhNhan(string mabn, string hbn, string tbn, string dc, Nullable<bool> gt, string khoa, string nhom, string bs, Nullable<int> sdt, Nullable<System.DateTime> ns)
        {
            var mabnParameter = mabn != null ?
                new ObjectParameter("mabn", mabn) :
                new ObjectParameter("mabn", typeof(string));
    
            var hbnParameter = hbn != null ?
                new ObjectParameter("hbn", hbn) :
                new ObjectParameter("hbn", typeof(string));
    
            var tbnParameter = tbn != null ?
                new ObjectParameter("tbn", tbn) :
                new ObjectParameter("tbn", typeof(string));
    
            var dcParameter = dc != null ?
                new ObjectParameter("dc", dc) :
                new ObjectParameter("dc", typeof(string));
    
            var gtParameter = gt.HasValue ?
                new ObjectParameter("gt", gt) :
                new ObjectParameter("gt", typeof(bool));
    
            var khoaParameter = khoa != null ?
                new ObjectParameter("khoa", khoa) :
                new ObjectParameter("khoa", typeof(string));
    
            var nhomParameter = nhom != null ?
                new ObjectParameter("nhom", nhom) :
                new ObjectParameter("nhom", typeof(string));
    
            var bsParameter = bs != null ?
                new ObjectParameter("bs", bs) :
                new ObjectParameter("bs", typeof(string));
    
            var sdtParameter = sdt.HasValue ?
                new ObjectParameter("sdt", sdt) :
                new ObjectParameter("sdt", typeof(int));
    
            var nsParameter = ns.HasValue ?
                new ObjectParameter("ns", ns) :
                new ObjectParameter("ns", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_Insert_BenhNhan", mabnParameter, hbnParameter, tbnParameter, dcParameter, gtParameter, khoaParameter, nhomParameter, bsParameter, sdtParameter, nsParameter);
        }
    
        public virtual int usp_insert_DT(string mdt, Nullable<int> sl, string hd, string mt, string bn)
        {
            var mdtParameter = mdt != null ?
                new ObjectParameter("mdt", mdt) :
                new ObjectParameter("mdt", typeof(string));
    
            var slParameter = sl.HasValue ?
                new ObjectParameter("sl", sl) :
                new ObjectParameter("sl", typeof(int));
    
            var hdParameter = hd != null ?
                new ObjectParameter("hd", hd) :
                new ObjectParameter("hd", typeof(string));
    
            var mtParameter = mt != null ?
                new ObjectParameter("mt", mt) :
                new ObjectParameter("mt", typeof(string));
    
            var bnParameter = bn != null ?
                new ObjectParameter("bn", bn) :
                new ObjectParameter("bn", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_insert_DT", mdtParameter, slParameter, hdParameter, mtParameter, bnParameter);
        }
    
        public virtual int usp_Insert_HD(string mhd, Nullable<System.DateTime> nl, string ngl, string bn, Nullable<System.DateTime> nk, string dv)
        {
            var mhdParameter = mhd != null ?
                new ObjectParameter("mhd", mhd) :
                new ObjectParameter("mhd", typeof(string));
    
            var nlParameter = nl.HasValue ?
                new ObjectParameter("nl", nl) :
                new ObjectParameter("nl", typeof(System.DateTime));
    
            var nglParameter = ngl != null ?
                new ObjectParameter("ngl", ngl) :
                new ObjectParameter("ngl", typeof(string));
    
            var bnParameter = bn != null ?
                new ObjectParameter("bn", bn) :
                new ObjectParameter("bn", typeof(string));
    
            var nkParameter = nk.HasValue ?
                new ObjectParameter("nk", nk) :
                new ObjectParameter("nk", typeof(System.DateTime));
    
            var dvParameter = dv != null ?
                new ObjectParameter("dv", dv) :
                new ObjectParameter("dv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_Insert_HD", mhdParameter, nlParameter, nglParameter, bnParameter, nkParameter, dvParameter);
        }
    
        public virtual int usp_Insert_Khoa(string mak, string tk)
        {
            var makParameter = mak != null ?
                new ObjectParameter("mak", mak) :
                new ObjectParameter("mak", typeof(string));
    
            var tkParameter = tk != null ?
                new ObjectParameter("tk", tk) :
                new ObjectParameter("tk", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_Insert_Khoa", makParameter, tkParameter);
        }
    
        public virtual int usp_Insert_NhanVien(string manv, string hnv, string tnv, Nullable<System.DateTime> ns, string dc, string sdt, Nullable<decimal> luong, Nullable<bool> gt, string nhom)
        {
            var manvParameter = manv != null ?
                new ObjectParameter("manv", manv) :
                new ObjectParameter("manv", typeof(string));
    
            var hnvParameter = hnv != null ?
                new ObjectParameter("hnv", hnv) :
                new ObjectParameter("hnv", typeof(string));
    
            var tnvParameter = tnv != null ?
                new ObjectParameter("tnv", tnv) :
                new ObjectParameter("tnv", typeof(string));
    
            var nsParameter = ns.HasValue ?
                new ObjectParameter("ns", ns) :
                new ObjectParameter("ns", typeof(System.DateTime));
    
            var dcParameter = dc != null ?
                new ObjectParameter("dc", dc) :
                new ObjectParameter("dc", typeof(string));
    
            var sdtParameter = sdt != null ?
                new ObjectParameter("sdt", sdt) :
                new ObjectParameter("sdt", typeof(string));
    
            var luongParameter = luong.HasValue ?
                new ObjectParameter("luong", luong) :
                new ObjectParameter("luong", typeof(decimal));
    
            var gtParameter = gt.HasValue ?
                new ObjectParameter("gt", gt) :
                new ObjectParameter("gt", typeof(bool));
    
            var nhomParameter = nhom != null ?
                new ObjectParameter("nhom", nhom) :
                new ObjectParameter("nhom", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_Insert_NhanVien", manvParameter, hnvParameter, tnvParameter, nsParameter, dcParameter, sdtParameter, luongParameter, gtParameter, nhomParameter);
        }
    
        public virtual int usp_Insert_Nhom(string manhom, string tn)
        {
            var manhomParameter = manhom != null ?
                new ObjectParameter("manhom", manhom) :
                new ObjectParameter("manhom", typeof(string));
    
            var tnParameter = tn != null ?
                new ObjectParameter("tn", tn) :
                new ObjectParameter("tn", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_Insert_Nhom", manhomParameter, tnParameter);
        }
    
        public virtual int usp_Restore_BenhNhan(string ma)
        {
            var maParameter = ma != null ?
                new ObjectParameter("ma", ma) :
                new ObjectParameter("ma", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_Restore_BenhNhan", maParameter);
        }
    
        public virtual ObjectResult<usp_Select_BacSi_Result> usp_Select_BacSi()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_Select_BacSi_Result>("usp_Select_BacSi");
        }
    
        public virtual ObjectResult<usp_Select_NhanVien_Result> usp_Select_NhanVien()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_Select_NhanVien_Result>("usp_Select_NhanVien");
        }
    
        public virtual ObjectResult<usp_Select_Nhom_Result> usp_Select_Nhom()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_Select_Nhom_Result>("usp_Select_Nhom");
        }
    
        public virtual int usp_Update_BacSi(string mabs, string hbs, string tbs, string dc, Nullable<System.DateTime> ns, Nullable<bool> gt, string sdt, string nhom, Nullable<decimal> luong, string khoa)
        {
            var mabsParameter = mabs != null ?
                new ObjectParameter("mabs", mabs) :
                new ObjectParameter("mabs", typeof(string));
    
            var hbsParameter = hbs != null ?
                new ObjectParameter("hbs", hbs) :
                new ObjectParameter("hbs", typeof(string));
    
            var tbsParameter = tbs != null ?
                new ObjectParameter("tbs", tbs) :
                new ObjectParameter("tbs", typeof(string));
    
            var dcParameter = dc != null ?
                new ObjectParameter("dc", dc) :
                new ObjectParameter("dc", typeof(string));
    
            var nsParameter = ns.HasValue ?
                new ObjectParameter("ns", ns) :
                new ObjectParameter("ns", typeof(System.DateTime));
    
            var gtParameter = gt.HasValue ?
                new ObjectParameter("gt", gt) :
                new ObjectParameter("gt", typeof(bool));
    
            var sdtParameter = sdt != null ?
                new ObjectParameter("sdt", sdt) :
                new ObjectParameter("sdt", typeof(string));
    
            var nhomParameter = nhom != null ?
                new ObjectParameter("nhom", nhom) :
                new ObjectParameter("nhom", typeof(string));
    
            var luongParameter = luong.HasValue ?
                new ObjectParameter("luong", luong) :
                new ObjectParameter("luong", typeof(decimal));
    
            var khoaParameter = khoa != null ?
                new ObjectParameter("khoa", khoa) :
                new ObjectParameter("khoa", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_Update_BacSi", mabsParameter, hbsParameter, tbsParameter, dcParameter, nsParameter, gtParameter, sdtParameter, nhomParameter, luongParameter, khoaParameter);
        }
    
        public virtual int usp_update_DT(string mdt, Nullable<int> sl, string hd, string mt, string bn)
        {
            var mdtParameter = mdt != null ?
                new ObjectParameter("mdt", mdt) :
                new ObjectParameter("mdt", typeof(string));
    
            var slParameter = sl.HasValue ?
                new ObjectParameter("sl", sl) :
                new ObjectParameter("sl", typeof(int));
    
            var hdParameter = hd != null ?
                new ObjectParameter("hd", hd) :
                new ObjectParameter("hd", typeof(string));
    
            var mtParameter = mt != null ?
                new ObjectParameter("mt", mt) :
                new ObjectParameter("mt", typeof(string));
    
            var bnParameter = bn != null ?
                new ObjectParameter("bn", bn) :
                new ObjectParameter("bn", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_update_DT", mdtParameter, slParameter, hdParameter, mtParameter, bnParameter);
        }
    
        public virtual int usp_Update_Khoa(string mak, string tk)
        {
            var makParameter = mak != null ?
                new ObjectParameter("mak", mak) :
                new ObjectParameter("mak", typeof(string));
    
            var tkParameter = tk != null ?
                new ObjectParameter("tk", tk) :
                new ObjectParameter("tk", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_Update_Khoa", makParameter, tkParameter);
        }
    
        public virtual int usp_Update_NhanVien(string manv, string hnv, string tnv, Nullable<System.DateTime> ns, string dc, string sdt, Nullable<decimal> luong, Nullable<bool> gt, string nhom)
        {
            var manvParameter = manv != null ?
                new ObjectParameter("manv", manv) :
                new ObjectParameter("manv", typeof(string));
    
            var hnvParameter = hnv != null ?
                new ObjectParameter("hnv", hnv) :
                new ObjectParameter("hnv", typeof(string));
    
            var tnvParameter = tnv != null ?
                new ObjectParameter("tnv", tnv) :
                new ObjectParameter("tnv", typeof(string));
    
            var nsParameter = ns.HasValue ?
                new ObjectParameter("ns", ns) :
                new ObjectParameter("ns", typeof(System.DateTime));
    
            var dcParameter = dc != null ?
                new ObjectParameter("dc", dc) :
                new ObjectParameter("dc", typeof(string));
    
            var sdtParameter = sdt != null ?
                new ObjectParameter("sdt", sdt) :
                new ObjectParameter("sdt", typeof(string));
    
            var luongParameter = luong.HasValue ?
                new ObjectParameter("luong", luong) :
                new ObjectParameter("luong", typeof(decimal));
    
            var gtParameter = gt.HasValue ?
                new ObjectParameter("gt", gt) :
                new ObjectParameter("gt", typeof(bool));
    
            var nhomParameter = nhom != null ?
                new ObjectParameter("nhom", nhom) :
                new ObjectParameter("nhom", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_Update_NhanVien", manvParameter, hnvParameter, tnvParameter, nsParameter, dcParameter, sdtParameter, luongParameter, gtParameter, nhomParameter);
        }
    
        public virtual int usp_Update_Nhom(string manhom, string tn)
        {
            var manhomParameter = manhom != null ?
                new ObjectParameter("manhom", manhom) :
                new ObjectParameter("manhom", typeof(string));
    
            var tnParameter = tn != null ?
                new ObjectParameter("tn", tn) :
                new ObjectParameter("tn", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_Update_Nhom", manhomParameter, tnParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual int usp_UndoBenhNhan(string ma)
        {
            var maParameter = ma != null ?
                new ObjectParameter("ma", ma) :
                new ObjectParameter("ma", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_UndoBenhNhan", maParameter);
        }
    
        public virtual int usp_Update_BenhNhan(string mabn, string hbn, string tbn, string dc, Nullable<bool> gt, string khoa, string nhom, string bs, Nullable<int> sdt, Nullable<System.DateTime> ns)
        {
            var mabnParameter = mabn != null ?
                new ObjectParameter("mabn", mabn) :
                new ObjectParameter("mabn", typeof(string));
    
            var hbnParameter = hbn != null ?
                new ObjectParameter("hbn", hbn) :
                new ObjectParameter("hbn", typeof(string));
    
            var tbnParameter = tbn != null ?
                new ObjectParameter("tbn", tbn) :
                new ObjectParameter("tbn", typeof(string));
    
            var dcParameter = dc != null ?
                new ObjectParameter("dc", dc) :
                new ObjectParameter("dc", typeof(string));
    
            var gtParameter = gt.HasValue ?
                new ObjectParameter("gt", gt) :
                new ObjectParameter("gt", typeof(bool));
    
            var khoaParameter = khoa != null ?
                new ObjectParameter("khoa", khoa) :
                new ObjectParameter("khoa", typeof(string));
    
            var nhomParameter = nhom != null ?
                new ObjectParameter("nhom", nhom) :
                new ObjectParameter("nhom", typeof(string));
    
            var bsParameter = bs != null ?
                new ObjectParameter("bs", bs) :
                new ObjectParameter("bs", typeof(string));
    
            var sdtParameter = sdt.HasValue ?
                new ObjectParameter("sdt", sdt) :
                new ObjectParameter("sdt", typeof(int));
    
            var nsParameter = ns.HasValue ?
                new ObjectParameter("ns", ns) :
                new ObjectParameter("ns", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_Update_BenhNhan", mabnParameter, hbnParameter, tbnParameter, dcParameter, gtParameter, khoaParameter, nhomParameter, bsParameter, sdtParameter, nsParameter);
        }
    
        public virtual ObjectResult<usp_ShowPhong_Result> usp_ShowPhong(string ma)
        {
            var maParameter = ma != null ?
                new ObjectParameter("ma", ma) :
                new ObjectParameter("ma", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ShowPhong_Result>("usp_ShowPhong", maParameter);
        }
    
        public virtual ObjectResult<Nullable<bool>> usp_DangNhap(string ten, string ma)
        {
            var tenParameter = ten != null ?
                new ObjectParameter("ten", ten) :
                new ObjectParameter("ten", typeof(string));
    
            var maParameter = ma != null ?
                new ObjectParameter("ma", ma) :
                new ObjectParameter("ma", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<bool>>("usp_DangNhap", tenParameter, maParameter);
        }
    
        public virtual ObjectResult<usp_Select_Khoa_Result> usp_Select_Khoa()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_Select_Khoa_Result>("usp_Select_Khoa");
        }
    
        public virtual ObjectResult<usp_Select_BenhAnNull_Result> usp_Select_BenhAnNull(string ma)
        {
            var maParameter = ma != null ?
                new ObjectParameter("ma", ma) :
                new ObjectParameter("ma", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_Select_BenhAnNull_Result>("usp_Select_BenhAnNull", maParameter);
        }
    
        public virtual ObjectResult<usp_Select_BenhAnNotNull_Result> usp_Select_BenhAnNotNull(string ma)
        {
            var maParameter = ma != null ?
                new ObjectParameter("ma", ma) :
                new ObjectParameter("ma", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_Select_BenhAnNotNull_Result>("usp_Select_BenhAnNotNull", maParameter);
        }
    
        public virtual ObjectResult<string> dk(string ma)
        {
            var maParameter = ma != null ?
                new ObjectParameter("ma", ma) :
                new ObjectParameter("ma", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("dk", maParameter);
        }
    
        public virtual int usp_Update_BenhAn(string maBA, string kqDieuTri, string noiDungKham, string tinhTrang, string huongDieuTri)
        {
            var maBAParameter = maBA != null ?
                new ObjectParameter("MaBA", maBA) :
                new ObjectParameter("MaBA", typeof(string));
    
            var kqDieuTriParameter = kqDieuTri != null ?
                new ObjectParameter("KqDieuTri", kqDieuTri) :
                new ObjectParameter("KqDieuTri", typeof(string));
    
            var noiDungKhamParameter = noiDungKham != null ?
                new ObjectParameter("NoiDungKham", noiDungKham) :
                new ObjectParameter("NoiDungKham", typeof(string));
    
            var tinhTrangParameter = tinhTrang != null ?
                new ObjectParameter("TinhTrang", tinhTrang) :
                new ObjectParameter("TinhTrang", typeof(string));
    
            var huongDieuTriParameter = huongDieuTri != null ?
                new ObjectParameter("HuongDieuTri", huongDieuTri) :
                new ObjectParameter("HuongDieuTri", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_Update_BenhAn", maBAParameter, kqDieuTriParameter, noiDungKhamParameter, tinhTrangParameter, huongDieuTriParameter);
        }
    
        public virtual ObjectResult<usp_ShowGiuong_Result> usp_ShowGiuong(string ma)
        {
            var maParameter = ma != null ?
                new ObjectParameter("ma", ma) :
                new ObjectParameter("ma", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ShowGiuong_Result>("usp_ShowGiuong", maParameter);
        }
    
        public virtual ObjectResult<usp_Info_Result> usp_Info(string ma)
        {
            var maParameter = ma != null ?
                new ObjectParameter("ma", ma) :
                new ObjectParameter("ma", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_Info_Result>("usp_Info", maParameter);
        }
    
        public virtual int usp_Insert_Giuong(string maG, string maP)
        {
            var maGParameter = maG != null ?
                new ObjectParameter("maG", maG) :
                new ObjectParameter("maG", typeof(string));
    
            var maPParameter = maP != null ?
                new ObjectParameter("maP", maP) :
                new ObjectParameter("maP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_Insert_Giuong", maGParameter, maPParameter);
        }
    
        public virtual ObjectResult<usp_ShowPNV_Result> usp_ShowPNV(string maG)
        {
            var maGParameter = maG != null ?
                new ObjectParameter("maG", maG) :
                new ObjectParameter("maG", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ShowPNV_Result>("usp_ShowPNV", maGParameter);
        }
    
        public virtual ObjectResult<usp_CheckMaDonThuoc_Result> usp_CheckMaDonThuoc(string ma)
        {
            var maParameter = ma != null ?
                new ObjectParameter("ma", ma) :
                new ObjectParameter("ma", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_CheckMaDonThuoc_Result>("usp_CheckMaDonThuoc", maParameter);
        }
    
        public virtual ObjectResult<usp_ShowBNChuaDT_Result> usp_ShowBNChuaDT()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ShowBNChuaDT_Result>("usp_ShowBNChuaDT");
        }
    
        public virtual ObjectResult<string> usp_BNChuaDT()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("usp_BNChuaDT");
        }
    
        public virtual ObjectResult<usp_ShowDT_Result> usp_ShowDT()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ShowDT_Result>("usp_ShowDT");
        }
    
        public virtual int usp_autoST(string name)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_autoST", nameParameter);
        }
    }
}
