//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLPK
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuXetNghiem
    {
        public string MaPXN { get; set; }
        public string TenLoaiXN { get; set; }
        public Nullable<System.DateTime> NgayXN { get; set; }
        public string KetQua { get; set; }
        public string GhiChu { get; set; }
        public string BenhNhan { get; set; }
        public Nullable<bool> Deleted { get; set; }
    
        public virtual BenhNhan BenhNhan1 { get; set; }
    }
}
