//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLPK
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuXuatVien
    {
        public string MaPXV { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public Nullable<System.DateTime> TgDieuTri { get; set; }
        public string Khoa { get; set; }
        public string BenhNhan { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public string NguoiLap { get; set; }
    
        public virtual BenhNhan BenhNhan1 { get; set; }
        public virtual Khoa Khoa1 { get; set; }
    }
}
