//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLPK
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Phong()
        {
            this.Giuongs = new HashSet<Giuong>();
        }
    
        public string MaPhong { get; set; }
        public string TenPhong { get; set; }
        public string Khoa { get; set; }
        public Nullable<int> SoGiuong { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Giuong> Giuongs { get; set; }
        public virtual Khoa Khoa1 { get; set; }
        public virtual Khoa Khoa2 { get; set; }
        public virtual Khoa Khoa3 { get; set; }
        public virtual Khoa Khoa4 { get; set; }
        public virtual Khoa Khoa5 { get; set; }
        public virtual Khoa Khoa6 { get; set; }
    }
}
