//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLPK
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Deleted_BenhNhan
    {
        public string MaBenhNhan { get; set; }
        public string HoBN { get; set; }
        public string TenBN { get; set; }
        public string DiaChi { get; set; }
        public Nullable<bool> GioiTinh { get; set; }
        public string Khoa { get; set; }
        public string Nhom { get; set; }
        public string BacSi { get; set; }
        public int SDT { get; set; }
        public System.DateTime NgaySinh { get; set; }
        public Nullable<bool> Deleted { get; set; }
    }
}
