//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLPK
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Select_BenhAnNull
    {
        public string MaBA { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public string KqDieuTri { get; set; }
        public string NoiDungKham { get; set; }
        public string TinhTrang { get; set; }
        public string HuongDieuTri { get; set; }
        public string BenhNhan { get; set; }
        public Nullable<bool> deleted { get; set; }
    }
}
